### ISSUE TITLE
Confused about Reverse Proxy Step

### ISSUE THREAD

**Issue by henrygrant** [LemmyNet/lemmy-docs#205]
https://join-lemmy.org/docs/en/administration/install_docker.html

```
To make Lemmy available outside the server, you need to set up a reverse proxy, like Nginx. You can use the following simple proxy:

Note: If you are planning on running your reverse proxy on port 80, you'll need to update the docker-compose.yml file you just downloaded to change the internal proxy's listening port. If you are setting up Let's Encrypt on the same machine, you'll need to do this.

server {
    listen 80;
    server_name my_domain.tld;

    location / {
        proxy_pass http://localhost:LEMMY_PORT;
        proxy_set_header Host $host;
        include proxy_params;
    }
}
```

I'm a little confused on this step. What exactly do I need to modify in the `docker-compose.yml` file, and where does this `server` block go, in `lemmy/nginx.conf` or the one in `/etc/nginx`? 

Would it be possible to get an example of what the configuration files should look like after you have certs from Let's Encrypt?

**Comment by AMoonRabbit** [comment]
You're not alone, I also came unstuck here. The server I was hoping to host this on already has other dockers running. The thing that I don't understand is the docker-compose file has both 80 and 443 mappings as `80:80` and `443:443`. But this obviously conflicts when you try to bring it up following the guide because those ports are already in use. 

The block you included above is the reverse proxy block, albeit it very basic. So would be in `/etc/nginx/sites-available` and symlinked or however you would do it. The thing is, the line `proxy_pass http://localhost:LEMMY_PORT;` also needs to be updated with the port number as there's nothing setting LEMMY_PORT, nor does it appear to be a variable at this point. But I may be being dumb.

**Comment by Nutomic** [comment]
Better use https://lemmy.ml/c/lemmy_support to get help.
