### ISSUE TITLE
[Request] Podman Install

### ISSUE THREAD

**Issue by Valinwolf** [LemmyNet/lemmy-docs#235]
I have attempted to use the podman-docker compatibility layer, however it seems that Lemmy's docker-compose file does something that is not supported by the compatibility layer. I do not want to use docker, as I already heavily use Podman and don't want waste system resources by running multiple containerization systems. This is the first docker-compose file that I have found creates errors.

So I guess my question is, are there any plans to add Podman support? I love Podman and it's daemonless approach to containerization.

**Comment by brettwilcox** [comment]
I would like to see this and Rancher Desktop support. It's something I can research at a future time.

**Comment by herzenschein** [comment]
> I have attempted to use the podman-docker compatibility layer, however it seems that Lemmy's docker-compose file does something that is not supported by the compatibility layer.

Can you elaborate on that?

I tried the [current instructions for Docker](https://join-lemmy.org/docs/administration/install_docker.html) with podman-compose and it worked fine. I just had to replace the {} placeholder variables with their actual values.

One thing I noticed was missing from the compose file was the :Z marker for SELinux which would otherwise not allow for extra themes in right volume to show up.

**Comment by Valinwolf** [comment]
I managed to find the issue, it was with the variables. Sorry I hadn’t managed to get back and close the issue.
