### ISSUE TITLE
Lemmy migration from a domain name to another

### ISSUE THREAD

**Issue by nicfab** [LemmyNet/lemmy-docs#271]
I want to migrate my Lemmy instance from one domain to another for security reasons.
How can I do it without losing all the contents?
I read this resource: https://join-lemmy.org/docs/administration/backup_and_restore.html, but I would appreciate more detailed instructions to avoid any issues.

**Comment by dessalines** [comment]
Thx! It might be a while before I get to this, so if anyone has done this in the past, I'd be happy to add their SQL commands to the doc above.

**Comment by Nutomic** [comment]
The documentation is correct, but somewhat outdated. Instead of `user_` table it should be `person`, and also some urls in `site` table need to be updated. You should also update the entry for your domain in `instance` table. That should be all, make sure you have backups before and after to revert in case something goes wrong. And please update the documentation once it works successfully.
