### ISSUE TITLE
Assign new administrators

### ISSUE THREAD

**Issue by dagheyman** [LemmyNet/lemmy-docs#38]
Is there a way in the UI to promote another user to admin?

**Comment by traverseda** [comment]
For the record (since this is still the first google result) you do it the same way you make someone a moderator. First they need to create a post, then you click the dot menu. You should have options like "feature post" and "appoint as moderator". It's described in the documentation here: https://join-lemmy.org/docs/en/users/04-moderation.html#how-to-moderate
